Calcul des descripteurs audio

In [ ]:
import os

from os import listdir
from os.path import isfile, join

import pandas as pd

from glob import glob

import librosa
import numpy as np

import matplotlib.pyplot as plt

from scipy.signal import hilbert, chirp

import scipy

import math

In [ ]:
#chargement des données du drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#Chargement du fichier avec la description des sons
data_dir_ini = '/content/drive/MyDrive/Article sound/audio/4_norm/'
audio_files_ini = glob(data_dir_ini+'/*.wav')

df = pd.read_table("/content/drive/MyDrive/Article sound/data/data_ini_2digits.csv", sep=',' , encoding='utf-8-sig')

In [ ]:
df

,sound_sample_name,sample,form,geol,hit_number,sample_name,sample_number,sound_sample_name_simple,sound_number,mass_ini,...,mass_n,mass_end,f1_ini,a1_ini,f1_0,a1_0,f1_n,a1_n,f1_end,a1_end
0,L_pl_a_1,L,pl,a,1,S01,1,S01_1,1,3458.07,...,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.756030,1.017641,2664.80616,0.637452
1,L_pl_a_2,L,pl,a,2,S01,1,S01_2,2,3458.07,...,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.756030,1.017641,2664.80616,0.637452
2,L_pl_a_3,L,pl,a,3,S01,1,S01_3,3,3458.07,...,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.756030,1.017641,2664.80616,0.637452
3,L_pl_a_4,L,pl,a,4,S01,1,S01_4,4,3458.07,...,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.756030,1.017641,2664.80616,0.637452
4,L_pl_a_5,L,pl,a,5,S01,1,S01_5,5,3458.07,...,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.756030,1.017641,2664.80616,0.637452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,P_pl_a_5,P,pl,a,5,S31,31,S31_5,5,1636.50,...,1656.34,1636.62,3020.0,0.4311,2943.0,0.3937,2854.714907,0.373521,2906.21575,0.454652
161,P_pl_a_6,P,pl,a,6,S31,31,S31_6,6,1636.50,...,1656.34,1636.62,3020.0,0.4311,2943.0,0.3937,2854.714907,0.373521,2906.21575,0.454652
162,P_pl_a_7,P,pl,a,7,S31,31,S31_7,7,1636.50,...,1656.34,1636.62,3020.0,0.4311,2943.0,0.3937,2854.714907,0.373521,2906.21575,0.454652
163,P_pl_a_8,P,pl,a,8,S31,31,S31_8,8,1636.50,...,1656.34,1636.62,3020.0,0.4311,2943.0,0.3937,2854.714907,0.373521,2906.21575,0.454652
164,P_pl_a_9,P,pl,a,9,S31,31,S31_9,9,1636.50,...,1656.34,1636.62,3020.0,0.4311,2943.0,0.3937,2854.714907,0.373521,2906.21575,0.454652

Calcul des descripteurs

In [ ]:
#Calcul du f1 audio
def compute_f1_audio(y, sr, n_fft, sound_name):
    # Compute F1 as the frequency with maximum intensity
    spectrum = abs(np.fft.fft(y))[0: int(len(y) / 2)]
    freqs = librosa.fft_frequencies(sr=sr, n_fft=n_fft)
    f1 = freqs[np.argmax(spectrum)]

    # Plots
    plt.plot(freqs[:-1], spectrum)
    plt.title(sound_name)
    plt.legend(["F1: " + '%.f' % f1])
    plt.show()
    print(sound_name, '\t', '%.f' % f1)


    return(f1)

In [ ]:
#Calcul du coefficient d'attenuation c et du facteur de qualité théorique (à partir de f1_audio et du facteur d'atténuation de l'enveloppe)

#Fonction pour déterminer l'enveloppe
def find_peaks_window(x, y, window):
    peak_x = []
    peak_vals = []
    n = len(y)
    for i in range(window, n - window):
        if (y[i] > np.max(y[i-window:i])) and (y[i] > np.max(y[i+1:i+1+window])):
            peak_x.append(x[i])
            peak_vals.append(y[i])
    return np.array(peak_x), np.array(peak_vals)

#Fonction de l'enveloppe
def monoExp(x, m, c, b):
    return m * np.exp(-c * x) + b

#Fit de l'enveloppe
def compute_damping(y, sr, sound_name):
    time = np.arange(len(y)) / sr

    peak_x, peak_vals = find_peaks_window(time, y, window=20)

    m0 = 1
    b0 = 0
    c0 = 1.0 / (peak_x[1] - peak_x[0])

    # perform the fit
    p0 = (m0, c0, b0)
    params, cv = scipy.optimize.curve_fit(monoExp, peak_x, peak_vals, p0, maxfev=2000)
    m, c, b = params

    # determine quality of the fit
    squaredDiffs = np.square(peak_vals - monoExp(peak_x, m, c, b))
    squaredDiffsFromMean = np.square(peak_vals - np.mean(peak_vals))
    rSquared = 1 - np.sum(squaredDiffs) / np.sum(squaredDiffsFromMean)
    print(f"R² = {rSquared}")

    # print the parameters
    print(f"Y = {m} * e^(-{c} * x) + {b}")

    plt.title(sound_name)

    plt.plot(time, y, zorder=1)

    plt.scatter(peak_x, peak_vals, color='green', label="Pics détectés")
    plt.plot(peak_x, monoExp(peak_x, m, c, b), '--', label="fitted", linewidth=2, zorder=10)

    plt.legend(f"R² = {rSquared}")

    plt.show()

    return c

Calcul des descripteurs

In [ ]:
audio_files_ini.sort()

for file in range(0, len(audio_files_ini),1):

    path = audio_files_ini[file]

    name = os.path.basename(path)
    name_simple = name.replace("_norm.wav", "")

    y, sr = librosa.load(path, sr=None)
    frame_lenght = len(y)
    row_index = df.loc[(df == name_simple).any(axis=1)].index[0]

    print('------------------------')
    print('\n', name_simple)

    plt.plot(np.arange(len(y)) / sr, y)
    plt.title(name_simple)
    plt.show()



    df.loc[row_index, "sound_path"] = path

    rms = librosa.feature.rms(y=y, S=None, frame_length=frame_lenght, center=False)[0][0]
    df.loc[row_index, "rms"] = rms

    centroid = librosa.feature.spectral_centroid(y=y, sr=sr, n_fft=frame_lenght, center=False, window='boxcar')[0][0]
    df.loc[row_index, "centroid"] = centroid

    flatness = librosa.feature.spectral_flatness(y=y, S=None, n_fft=frame_lenght, center=False, window='boxcar')[0][0]

    df.loc[row_index, "flatness"] = flatness

    rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr, n_fft=frame_lenght, center=False, window='boxcar')[0][0]

    df.loc[row_index, "rolloff"] = rolloff

    contrast = librosa.feature.spectral_contrast(y=y, sr=sr, n_fft=frame_lenght, center=False, n_bands=1, window='boxcar')[0][0]

    df.loc[row_index, "contrast"] = contrast

    f1 = compute_f1_audio(y, sr, frame_lenght, name_simple)

    df.loc[row_index, "f1_audio"] = f1

    c = compute_damping(y, sr, name_simple)
    df.loc[row_index, "c"] = c

    Q= (3.14 * f1 )/c
    df.loc[row_index, "Q"] = Q

    print("RMS: ", rms)
    print("Centroid: ", centroid)
    print("Flatness: ", flatness)
    print("Rolloff: ", rolloff)
    print("Contrast: ", contrast)
    print("F1: ", f1)
    print("c: ", c)
    print("Q: ", Q)

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
df

,sound_sample_name,sample,form,geol,hit_number,sample_name,sample_number,sound_sample_name_simple,sound_number,mass_ini,...,a1_end,sound_path,rms,centroid,flatness,rolloff,contrast,f1_audio,c,Q
0,L_pl_a_1,L,pl,a,1,S01,1,S01_1,1,3458.07,...,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.122204,5841.668799,0.008963,12397.290432,14.673802,3223.793395,55.140871,183.579095
1,L_pl_a_2,L,pl,a,2,S01,1,S01_2,2,3458.07,...,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.129421,6028.623430,0.007643,14052.751905,10.566528,3227.942422,59.485896,170.388946
2,L_pl_a_3,L,pl,a,3,S01,1,S01_3,3,3458.07,...,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.111234,6446.748089,0.012436,16177.053345,12.863068,3223.793395,57.890860,174.858539
3,L_pl_a_4,L,pl,a,4,S01,1,S01_4,4,3458.07,...,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.128124,6010.692139,0.008403,13538.272650,14.208599,3227.942422,63.182687,160.419565
4,L_pl_a_5,L,pl,a,5,S01,1,S01_5,5,3458.07,...,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.130879,6893.026751,0.013390,16525.571550,19.863773,3227.942422,60.316329,168.043038
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,P_pl_a_5,P,pl,a,5,S31,31,S31_5,5,1636.50,...,0.454652,/content/drive/MyDrive/Article sound/audio/4_n...,0.186941,6135.595823,0.003788,13310.076207,16.549231,3456.138865,26.039233,416.766354
161,P_pl_a_6,P,pl,a,6,S31,31,S31_6,6,1636.50,...,0.454652,/content/drive/MyDrive/Article sound/audio/4_n...,0.174533,5758.063079,0.003231,9463.928874,16.699080,3456.138865,26.775503,405.306146
162,P_pl_a_7,P,pl,a,7,S31,31,S31_7,7,1636.50,...,0.454652,/content/drive/MyDrive/Article sound/audio/4_n...,0.129668,4726.509981,0.000583,6634.292972,20.380640,3451.989839,26.909441,402.804655
163,P_pl_a_8,P,pl,a,8,S31,31,S31_8,8,1636.50,...,0.454652,/content/drive/MyDrive/Article sound/audio/4_n...,0.201567,5464.058606,0.002583,8414.225233,13.928079,3456.138865,24.830045,437.062279
164,P_pl_a_9,P,pl,a,9,S31,31,S31_9,9,1636.50,...,0.454652,/content/drive/MyDrive/Article sound/audio/4_n...,0.157036,4692.989267,0.001897,5688.314987,6.550501,3451.989839,22.767452,476.085241

Evaluation de l'endommagement et création des labels

In [ ]:
#Evaluation de l'endommagement et création des labels
for file in range(0, len(audio_files_ini),1):

    path = audio_files_ini[file]
    name = os.path.basename(path)
    name_simple = name.replace("_norm.wav", "")

    row_index = df.loc[(df == name_simple).any(axis=1)].index[0]

    #Endommagement final = 1-RDEMfrost
    df.loc[row_index, "D"] = 1-((df.loc[row_index, "f1_n"])*(df.loc[row_index, "f1_n"]))/((df.loc[row_index, "f1_0"])*(df.loc[row_index, "f1_0"]))

    #Facteur de qualité
    df.loc[row_index, "Q_vibration_initial"] = (1/(2*df.loc[row_index, "a1_0"]))*100   #Facteur de qualité initial

    #Pour D_01
    df.loc[row_index, "frost_resistant_01"] = 1 if df.loc[row_index, "D"] < 0.1 else 0

    #Pour D_001
    df.loc[row_index, "frost_resistant_001"] = 1 if df.loc[row_index, "D"] < 0.01 else 0

/tmp/ipykernel_18410/3471500268.py:11: RuntimeWarning: invalid value encountered in scalar divide
  df.loc[row_index, "D"] = 1-((df.loc[row_index, "f1_n"])*(df.loc[row_index, "f1_n"]))/((df.loc[row_index, "f1_0"])*(df.loc[row_index, "f1_0"]))
/tmp/ipykernel_18410/3471500268.py:14: RuntimeWarning: divide by zero encountered in scalar divide
  df.loc[row_index, "Q_vibration_initial"] = (1/(2*df.loc[row_index, "a1_0"]))*100   #Facteur de qualité initial

In [ ]:
pd.options.display.max_columns = None
df.head()

,sound_sample_name,sample,form,geol,hit_number,sample_name,sample_number,sound_sample_name_simple,sound_number,mass_ini,mass_0,mass_n,mass_end,f1_ini,a1_ini,f1_0,a1_0,f1_n,a1_n,f1_end,a1_end,sound_path,rms,centroid,flatness,rolloff,contrast,f1_audio,c,Q,D,Q_vibration_initial,frost_resistant_01,frost_resistant_001
0,L_pl_a_1,L,pl,a,1,S01,1,S01_1,1,3458.07,3481.07,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.75603,1.017641,2664.80616,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.122204,5841.668799,0.008963,12397.290432,14.673802,3223.793395,55.140871,183.579095,0.068472,68.785252,1.0,0.0
1,L_pl_a_2,L,pl,a,2,S01,1,S01_2,2,3458.07,3481.07,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.75603,1.017641,2664.80616,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.129421,6028.623430,0.007643,14052.751905,10.566528,3227.942422,59.485896,170.388946,0.068472,68.785252,1.0,0.0
2,L_pl_a_3,L,pl,a,3,S01,1,S01_3,3,3458.07,3481.07,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.75603,1.017641,2664.80616,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.111234,6446.748089,0.012436,16177.053345,12.863068,3223.793395,57.890860,174.858539,0.068472,68.785252,1.0,0.0
3,L_pl_a_4,L,pl,a,4,S01,1,S01_4,4,3458.07,3481.07,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.75603,1.017641,2664.80616,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.128124,6010.692139,0.008403,13538.272650,14.208599,3227.942422,63.182687,160.419565,0.068472,68.785252,1.0,0.0
4,L_pl_a_5,L,pl,a,5,S01,1,S01_5,5,3458.07,3481.07,3481.78,3460.54,2748.0,0.3712,2590.0,0.7269,2499.75603,1.017641,2664.80616,0.637452,/content/drive/MyDrive/Article sound/audio/4_n...,0.130879,6893.026751,0.013390,16525.571550,19.863773,3227.942422,60.316329,168.043038,0.068472,68.785252,1.0,0.0

Exportation des données par son en CSV

In [ ]:
# Exporter en CSV sans l’index
df.to_csv('/content/drive/MyDrive/Article sound/data/sound_features.csv', index=False, encoding='utf-8')

Exportation des données par échantillon

In [ ]:
frost_resistant_01 = (df.groupby("sample_name")["frost_resistant_01"]
          .apply(list)
          .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
          .add_prefix("frost_resitant_0"))

frost_resistant_001 = (df.groupby("sample_name")["frost_resistant_001"]
            .apply(list)
            .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
            .add_prefix("frost_resitant_00"))

form = (df.groupby("sample_name")["form"]
            .apply(list)
            .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
            .add_prefix("form_"))

f1_vibration = (df.groupby("sample_name")["f1_ini"]
          .apply(list)
          .apply(max)
          .to_frame(name="f1_vibration"))

centroid = (df.groupby("sample_name")["centroid"]
          .apply(list)
          .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
          .add_prefix("centroid_"))

rms = (df.groupby("sample_name")["rms"]
          .apply(list)
          .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
          .add_prefix("rms_"))

flatness = (df.groupby("sample_name")["flatness"]
            .apply(list)
            .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
            .add_prefix("flatness_"))

rolloff = (df.groupby("sample_name")["rolloff"]
          .apply(list)
          .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
          .add_prefix("rolloff_"))

contrast = (df.groupby("sample_name")["contrast"]
            .apply(list)
            .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
            .add_prefix("contrast_"))

f1_audio = (df.groupby("sample_name")["f1_audio"]
            .apply(list)
            .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
            .add_prefix("f1_audio_"))

c = (df.groupby("sample_name")["c"]
          .apply(list)
          .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
          .add_prefix("c_"))

Q = (df.groupby("sample_name")["Q"]
          .apply(list)
          .apply(lambda x: pd.Series(x, index=range(1, len(x)+1)))
          .add_prefix("Q_"))


out = pd.concat([frost_resistant_01["frost_resitant_01"], frost_resistant_001["frost_resitant_001"], form["form_1"], f1_vibration, rms, flatness, rolloff, contrast, f1_audio, c, centroid, Q], axis=1).reset_index()
out = out.fillna("")

print(out)

   sample_name frost_resitant_01 frost_resitant_001 form_1  f1_vibration  \
0          S01               1.0                0.0     pl   2748.000000
1          S02               1.0                0.0     pl   3289.000000
2          S03               1.0                0.0     pl   1665.211513
3          S04               1.0                0.0     pt   5750.000000
4          S05               1.0                0.0     pt   5372.000000
5          S06               1.0                0.0     pt   5804.000000
6          S07               1.0                0.0     pt   5447.000000
7          S08               1.0                1.0     pt   3370.000000
8          S09               1.0                1.0     pt   3622.000000
9          S10               1.0                0.0     pt   3115.000000
10         S11               0.0                0.0     pl   2014.886014
11         S12               0.0                0.0     pl   1531.468471
12         S13               1.0                1.0     pl   2060.244079
13         S14               1.0                0.0     pl   3058.309851
14         S15               1.0                1.0     pl   2825.273540
15         S16               0.0                0.0     pt   4472.000000
16         S17               1.0                0.0     pt   4498.000000
17         S18               1.0                1.0     pt   4719.000000
18         S19               1.0                1.0     pt   4536.000000
19         S20               0.0                0.0     pt   4571.000000
20         S21               1.0                1.0     pt   4823.929005
21         S22               1.0                1.0     pt   6597.000000
22         S23               1.0                1.0     pt   6197.000000
23         S24               1.0                1.0     pt   6406.000000
24         S25               0.0                0.0     pl   2384.185089
25         S26               0.0                0.0     pl   3740.000000
26         S27               0.0                0.0     pt   9348.000000
27         S28               0.0                0.0     pt   8478.000000
28         S29                                          pt   9207.000000
29         S30               1.0                1.0     pl   3271.000000
30         S31               1.0                0.0     pl   3020.000000

       rms_1     rms_2     rms_3     rms_4     rms_5     rms_6     rms_7  \
0   0.122204  0.129421  0.111234  0.128124  0.130879  0.114371  0.101053
1   0.118736  0.145612  0.109484  0.137154  0.138425   0.13242  0.109408
2   0.105056  0.118863  0.093317  0.106551  0.100342   0.09387  0.106784
3   0.103743  0.107076  0.106194
4   0.106428  0.103779  0.109662
5   0.102041  0.102716  0.102248
6   0.117247  0.121782
7   0.150835  0.161233  0.144541
8    0.14204  0.136088  0.133269
9   0.139613  0.143177  0.131833
10   0.10425  0.119245  0.095665  0.095566  0.122176  0.116533  0.100599
11  0.100455  0.116074  0.106657  0.132255  0.124468  0.142716  0.104147
12  0.102669  0.147456  0.094925  0.109437  0.125394  0.118772  0.109486
13  0.113748  0.155692  0.108589  0.148485  0.149526  0.120295  0.105627
14  0.112983  0.147976  0.109003  0.115212  0.142412   0.12917  0.117977
15  0.094983  0.103072  0.095272
16  0.138445  0.136462  0.133319
17  0.126957  0.125633  0.126339
18  0.130424  0.128729  0.128873
19  0.131623  0.132341   0.13516
20   0.12705  0.122466  0.123538
21  0.113047  0.109769  0.109336
22  0.114594  0.117707  0.114964
23  0.114091  0.118094  0.114941
24   0.14302  0.174143  0.109386  0.150022  0.130951  0.124913  0.124554
25  0.115215  0.124276  0.088052  0.118328            0.122534  0.112984
26  0.099292            0.094538
27  0.107934
28            0.092604  0.084747
29  0.120115  0.165046   0.13148  0.163405   0.17257  0.146175   0.13003
30  0.155497  0.190644  0.127823  0.196311  0.186941  0.174533  0.129668

       rms_8     rms_9 flatness_1 flatness_2 flatness_3 flatness_4 flatness_5  \
0   0.122191  0.103574   0.008963   0.007643   0.012436   0.008403    0.01339
1   0.147778  0.134464   0.016339   0.015454   0.006394   0.015358   0.027054
2     0.0855  0.091838    0.00994   0.009023   0.006666   0.006019   0.006953
3                         0.03596   0.016435   0.009913
4                        0.013317   0.009995   0.005318
5                        0.010802    0.00821   0.009769
6                         0.01334   0.007979
7                        0.002789   0.002782   0.004641
8                        0.005419    0.00554   0.005293
9                        0.007038   0.007549   0.007382
10  0.108498  0.093699    0.00587   0.006452   0.007453   0.004532   0.006173
11  0.094522  0.068557   0.011616   0.005616   0.012631   0.006446   0.013471
12  0.134071  0.092488   0.007487   0.006481   0.001893   0.006627   0.007379
13  0.162624  0.122447   0.005138   0.005589   0.005108   0.003549   0.004283
14  0.142653    0.1146   0.002165   0.003642    0.01038   0.005803   0.023006
15                        0.03421   0.030737   0.074818
16                       0.009528   0.006342   0.005917
17                       0.013947   0.010877    0.01438
18                       0.005106   0.006342   0.002796
19                       0.004457   0.006075   0.009662
20                       0.005835   0.006418   0.006263
21                       0.052445   0.019505   0.049594
22                       0.004668   0.010289    0.00796
23                       0.023389   0.007928   0.006525
24  0.122897  0.146903   0.018643   0.007926   0.022913    0.00206   0.007253
25  0.129852  0.105226   0.080425   0.048385   0.018376   0.045927
26                       0.021149              0.027828
27                        0.01574
28                                  0.066821   0.024149
29   0.18133  0.165057   0.015405   0.006395   0.124783    0.00573   0.004952
30  0.201567  0.157036   0.007652   0.002176   0.000994   0.001298   0.003788

   flatness_6 flatness_7 flatness_8 flatness_9     rolloff_1     rolloff_2  \
0    0.014131   0.012329   0.007448   0.002556  12397.290432  14052.751905
1    0.011955    0.00697   0.007724   0.006021  18280.609653  18268.162574
2    0.002398   0.012777   0.012875   0.005959  13911.685013  15558.848434
3                                               18550.296359   15231.07536
4                                               13795.512278  10716.934801
5                                               10712.785775   8576.037257
6                                               15948.856901  11173.327688
7                                                7551.227773   7638.357324
8                                               10625.656224   9360.203218
9                                               12857.832345  13214.648603
10     0.0059   0.006881   0.022316     0.0059   6605.249788   8621.676545
11   0.007241   0.011885    0.02666   0.030889  14318.289585   7966.130398
12   0.011169   0.004062   0.004308   0.008113  13550.719729  13716.680779
13   0.004969   0.002456   0.002549   0.027893   7808.467401  12886.875529
14    0.00756   0.006217   0.004652   0.001999   6397.798476   9617.442845
15                                              18147.840813  17994.326842
16                                              15903.217612  10057.239627
17                                              17110.584251  16114.817951
18                                               8646.570703    9368.50127
19                                               8015.918713   9696.274344
20                                               8580.186283   9248.179509
21                                               19102.11685  16786.960203
22                                               7547.078747  12326.756986
23                                              17608.467401  10584.165961
24   0.006325   0.006333   0.004118   0.002693  18210.076207  17450.804403
25   0.012956   0.010283   0.010081   0.016101  19537.764606  19176.799323
26                                              15766.299746
27                                              14372.226926
28                                                            18786.790855
29   0.013006   0.003389   0.010797   0.005816  16807.705334  16521.422523
30   0.003231   0.000583   0.002583   0.001897  15255.969517   8629.974598

       rolloff_3     rolloff_4     rolloff_5     rolloff_6     rolloff_7  \
0   16177.053345   13538.27265   16525.57155  14973.835732  10887.044877
1   10787.468247  17600.169348  18741.151566  16089.923793   8679.762913
2    6837.595258   6879.085521   7609.314141   4742.337003  16214.394581
3   11185.774767
4    7285.690093
5     9999.15326
6
7    10065.53768
8    9517.866215
9   10521.930567
10   7903.895004   6099.068586  12837.087214   7638.357324   6538.865368
11  15488.314987   12907.62066  15276.714649  12762.404742  13152.413209
12   4850.211685  10252.243861  11210.668925  11140.135478   5323.200677
13    8837.42591   8787.637595  10455.546147   7625.910246   6588.653683
14   9596.697714   8683.911939   18537.84928  11579.932261   7480.694327
15  19093.818798
16   9725.317528
17  16608.552075
18   5982.895851
19  14260.203218
20   9517.866215
21   19135.30906
22   9629.889924
23    8671.46486
24  18264.013548   5804.487722  10501.185436   8642.421677    8638.27265
25  12380.694327   19002.54022                14886.706181  12181.541067
26  16438.441998
27
28  15621.083827
29  19894.580864  14239.458086  15421.930567  17529.635902   7447.502117
30   6663.336156   5916.511431  13310.076207   9463.928874   6634.292972

       rolloff_8     rolloff_9 contrast_1 contrast_2 contrast_3 contrast_4  \
0   10633.954276   6397.798476  14.673802  10.566528  12.863068  14.208599
1   16152.159187  10376.714649  29.826742   18.81998  18.723538   18.68509
2   13650.296359     5895.7663  15.193014   17.11473  14.292372  10.734138
3                               13.438899  12.800314   8.528069
4                               19.972425   8.571825   8.611889
5                                9.612124   9.810438  12.262222
6                                23.10515  13.044374
7                               10.234696  10.287005   9.030489
8                               10.273424  11.948557  21.313224
9                               15.312898  16.150865  17.145273
10  17060.795936   5866.723116  12.176044  10.613703   16.66669  11.456381
11   17708.04403   13106.77392   13.97852   5.951706   8.371173  11.776179
12  10920.237087    9235.73243  32.698047  17.735567  22.369521  29.104753
13   6717.273497  18541.998307  25.539034  14.402887  11.473142  14.388196
14   8368.585944    6526.41829   12.70381  16.358749   8.391772  11.061809
15                              20.406481  27.151993  27.413262
16                               14.53502   28.75912  13.660844
17                              18.808423   19.82797  21.219746
18                              10.644724  14.040388   8.113745
19                               7.596514  14.895237  10.995869
20                              12.808549  15.508485  14.223432
21                              22.906351  16.898246  13.081366
22                              13.666892   13.69739  12.059372
23                              15.435573   18.95926  14.716827
24   8198.475868  11036.409822  18.344333   8.993769  21.515236  12.250224
25  14953.090601  16338.865368   26.87823  14.891165  16.011248  19.775155
26                              10.016974             11.283894
27                               9.728752
28                                         13.094887  16.838899
29  18064.860288  13629.551228  11.409059  10.920796  23.700935  13.110906
30   8414.225233   5688.314987  12.606471  12.163533   8.684323  11.172595

   contrast_5 contrast_6 contrast_7 contrast_8 contrast_9   f1_audio_1  \
0   19.863773  13.529413  13.348872  16.384968  15.057705  3223.793395
1   30.014621  17.509814  11.260597  20.458865  12.831292  3315.071973
2   21.940421   8.499996  14.247616  17.561312   5.571778  3900.084674
3                                                          5750.550381
4                                                          5368.839966
5                                                          5808.636749
6                                                          5451.820491
7                                                           3339.96613
8                                                          3622.099915
9                                                          3082.726503
10  13.129172  15.512696   7.676709  19.708781   9.113271  4485.097375
11   20.23763  13.037315  14.540281  17.304007  18.512992  2219.729043
12  15.513014    17.8851  12.150716  11.810321  15.749991  2402.286198
13  11.455092  19.340598  13.399599   6.989989  15.354504  3617.950889
14  17.509511  16.798596   6.911676  10.550343  13.066533  3310.922947
15                                                         4476.799323
16                                                         4497.544454
17                                                         4721.591871
18                                                         4522.438611
19                                                         4580.524979
20                                                         4821.168501
21                                                         6601.100762
22                                                          6194.49619
23                                                         6410.245555
24  20.018154  11.144612  11.168882  15.732931  16.021912  2837.933954
25             17.318478   12.25552  14.846602  16.150298  3754.868755
26                                                         9430.736664
27                                                          8937.00254
28
29  10.228563   10.58573   8.574294  14.671664  19.049389  3833.700254
30  16.549231   16.69908   20.38064  13.928079   6.550501  3456.138865

     f1_audio_2   f1_audio_3   f1_audio_4   f1_audio_5   f1_audio_6  \
0   3227.942422  3223.793395  3227.942422  3227.942422  3227.942422
1   3593.056732  3315.071973  3593.056732  3593.056732  3593.056732
2   1788.230313  3900.084674  3900.084674  1788.230313  3900.084674
3   5750.550381  5750.550381
4   5368.839966  5368.839966
5   5808.636749  5808.636749
6   5451.820491
7    3339.96613   3339.96613
8   3622.099915  3622.099915
9   3082.726503  3082.726503
10  2348.348857  4485.097375  4485.097375  2348.348857  2348.348857
11  2219.729043  2219.729043  2219.729043  2219.729043  2219.729043
12  2402.286198  4592.972058  2402.286198  2402.286198  2402.286198
13  3617.950889  3617.950889  3617.950889  3617.950889  3617.950889
14  3310.922947  3310.922947  3310.922947  3310.922947  3310.922947
15   4468.50127   4468.50127
16  4497.544454   4501.69348
17  4721.591871  4721.591871
18  4522.438611  4522.438611
19  4580.524979  4580.524979
20  4821.168501  4821.168501
21  6601.100762  6601.100762
22   6194.49619   6194.49619
23  6406.096528  6406.096528
24  2837.933954  2837.933954  2837.933954  2837.933954  2837.933954
25  5169.686706  3750.719729  5169.686706               5169.686706
26               9430.736664
27
28  9526.164268  9522.015241
29  3833.700254  3286.028789  3833.700254  3833.700254  3833.700254
30  3456.138865  3451.989839  3456.138865  3456.138865  3456.138865

     f1_audio_7   f1_audio_8   f1_audio_9         c_1         c_2         c_3  \
0   3223.793395  3223.793395  3223.793395   55.140871   59.485896    57.89086
1   3315.071973  3593.056732  3315.071973   53.590213   55.768092   52.344184
2   1788.230313  1788.230313  3895.935648   56.806662    44.97485   59.088341
3                                          104.057411  103.448224   96.625126
4                                           95.872463   95.976631    86.70923
5                                          110.161899  104.201227  103.432419
6                                           68.654684   67.570562
7                                           43.730744   42.526667   43.138527
8                                           55.755492   55.517256   53.960332
9                                           51.011316   50.166816   55.983247
10  4485.097375  2348.348857  2348.348857   63.236134   35.206797    65.29981
11  2219.729043  2219.729043  2219.729043   57.517338   50.490533    46.14107
12  2402.286198  2402.286198  2070.364098   41.447797   41.789584   53.638975
13  3617.950889  3617.950889  3066.130398   41.828876   44.444487   40.877982
14  2837.933954  3310.922947  2837.933954   43.756374   42.191975   43.705062
15                                         106.622116  116.556114  128.154731
16                                          60.258058   61.271529   60.495405
17                                          67.868074   69.889158   65.695792
18                                           61.50226   63.023199   60.334882
19                                          62.668975   62.197148   61.854314
20                                          70.954715   71.705148   69.956652
21                                          90.887183   88.762793   93.336582
22                                          81.761156   77.128605   85.403333
23                                          83.667337   80.818163   88.726083
24  2837.933954  2837.933954  2837.933954   34.289812    34.33738   42.814239
25  3750.719729   5165.53768  3754.868755   55.452848   68.567037   55.168118
26                                         101.614609              108.548707
27                                          91.704182
28                                                      96.126802   121.38828
29  3833.700254  3833.700254  3833.700254   30.790683   30.241608   32.068281
30  3451.989839  3456.138865  3451.989839   24.902175   25.407826   26.465602

          c_4        c_5        c_6        c_7        c_8        c_9  \
0   63.182687  60.316329  66.255863  59.274832  64.133336   58.61262
1   52.534777  56.854063  54.397365  52.550665  48.540497  56.479053
2   51.434448  58.481212  62.897749  44.583643  54.349873  55.834852
3
4
5
6
7
8
9
10  63.833656  36.773212  47.940787  56.736038  29.790426  57.468531
11  42.779974  45.962235  41.779624  53.020507  49.275712  60.084041
12  48.615728  51.771745  46.529697  44.006336  42.939184  47.791097
13  44.034305  43.510702  48.552634  42.233956  41.369253  41.985465
14  47.092386  44.280407   42.86763  40.395283  43.657784  38.609247
15
16
17
18
19
20
21
22
23
24  34.010678    39.9904  34.104253  34.477962   33.54653  28.427882
25  60.961888             59.379477  47.599912  71.497111  50.255225
26
27
28
29  30.893915   31.06829  34.787812  29.374213  30.207505  27.291869
30  25.914227  26.039233  26.775503  26.909441  24.830045  22.767452

      centroid_1    centroid_2    centroid_3   centroid_4   centroid_5  \
0    5841.668799    6028.62343   6446.748089  6010.692139  6893.026751
1    7814.978773   7963.651772   5625.709233  7481.775787  8567.668763
2    6197.090933   5959.802284   5035.394561   5013.24937  5459.173114
3    9268.764887   8021.454829   7279.460418
4      7666.6358   7107.350129   6278.363827
5     7280.09518   6869.146299   7196.536766
6    8143.358876   7246.237426
7     5078.51954   5171.122317   5792.681481
8    5826.901464   5596.319438   5651.561697
9    5975.269696   6066.656816   5823.560949
10   5217.113024   5137.834911   5514.998015  5157.252595  5588.141712
11    6190.11629   5114.221455    6283.44372  5552.158382  6341.669443
12   5590.773533   5725.229728   4822.739894  5662.294952  5636.014397
13   5637.890669   6119.027133   5559.983572  5598.390402  5806.685858
14   4888.922728   5413.182118   5475.279215   5602.58452  8246.671452
15   8243.048705   8179.077191   9401.664029
16   7187.299313   6364.293998   6269.550554
17   7774.523108   7321.516971   7871.221624
18   6148.651569       6257.74   5380.478478
19   6089.135049   6370.570835   7178.409083
20   6257.254237   6420.425096   6495.697888
21  10046.854175   9024.661848  10060.389593

In [ ]:
out

,sample_name,frost_resitant_01,frost_resitant_001,form_1,f1_vibration,rms_1,rms_2,rms_3,rms_4,rms_5,rms_6,rms_7,rms_8,rms_9,flatness_1,flatness_2,flatness_3,flatness_4,flatness_5,flatness_6,flatness_7,flatness_8,flatness_9,rolloff_1,rolloff_2,rolloff_3,rolloff_4,rolloff_5,rolloff_6,rolloff_7,rolloff_8,rolloff_9,contrast_1,contrast_2,contrast_3,contrast_4,contrast_5,contrast_6,contrast_7,contrast_8,contrast_9,f1_audio_1,f1_audio_2,f1_audio_3,f1_audio_4,f1_audio_5,f1_audio_6,f1_audio_7,f1_audio_8,f1_audio_9,c_1,c_2,c_3,c_4,c_5,c_6,c_7,c_8,c_9,centroid_1,centroid_2,centroid_3,centroid_4,centroid_5,centroid_6,centroid_7,centroid_8,centroid_9,Q_1,Q_2,Q_3,Q_4,Q_5,Q_6,Q_7,Q_8,Q_9
0,S01,1.0,0.0,pl,2748.000000,0.122204,0.129421,0.111234,0.128124,0.130879,0.114371,0.101053,0.122191,0.103574,0.008963,0.007643,0.012436,0.008403,0.01339,0.014131,0.012329,0.007448,0.002556,12397.290432,14052.751905,16177.053345,13538.27265,16525.57155,14973.835732,10887.044877,10633.954276,6397.798476,14.673802,10.566528,12.863068,14.208599,19.863773,13.529413,13.348872,16.384968,15.057705,3223.793395,3227.942422,3223.793395,3227.942422,3227.942422,3227.942422,3223.793395,3223.793395,3223.793395,55.140871,59.485896,57.89086,63.182687,60.316329,66.255863,59.274832,64.133336,58.61262,5841.668799,6028.62343,6446.748089,6010.692139,6893.026751,6581.526085,5742.024542,5688.223022,4881.061628,183.579095,170.388946,174.858539,160.419565,168.043038,152.978751,170.775874,157.838526,172.70532
1,S02,1.0,0.0,pl,3289.000000,0.118736,0.145612,0.109484,0.137154,0.138425,0.13242,0.109408,0.147778,0.134464,0.016339,0.015454,0.006394,0.015358,0.027054,0.011955,0.00697,0.007724,0.006021,18280.609653,18268.162574,10787.468247,17600.169348,18741.151566,16089.923793,8679.762913,16152.159187,10376.714649,29.826742,18.81998,18.723538,18.68509,30.014621,17.509814,11.260597,20.458865,12.831292,3315.071973,3593.056732,3315.071973,3593.056732,3593.056732,3593.056732,3315.071973,3593.056732,3315.071973,53.590213,55.768092,52.344184,52.534777,56.854063,54.397365,52.550665,48.540497,56.479053,7814.978773,7963.651772,5625.709233,7481.775787,8567.668763,7020.566623,5358.211364,6684.951085,5688.567321,194.239311,202.305613,198.863085,214.756752,198.441371,207.403396,198.081716,232.428568,184.304188
2,S03,1.0,0.0,pl,1665.211513,0.105056,0.118863,0.093317,0.106551,0.100342,0.09387,0.106784,0.0855,0.091838,0.00994,0.009023,0.006666,0.006019,0.006953,0.002398,0.012777,0.012875,0.005959,13911.685013,15558.848434,6837.595258,6879.085521,7609.314141,4742.337003,16214.394581,13650.296359,5895.7663,15.193014,17.11473,14.292372,10.734138,21.940421,8.499996,14.247616,17.561312,5.571778,3900.084674,1788.230313,3900.084674,3900.084674,1788.230313,3900.084674,1788.230313,1788.230313,3895.935648,56.806662,44.97485,59.088341,51.434448,58.481212,62.897749,44.583643,54.349873,55.834852,6197.090933,5959.802284,5035.394561,5013.24937,5459.173114,4558.928434,6193.474734,6016.156455,4705.888714,215.577989,124.848513,207.253506,238.094629,96.01448,194.701178,125.944018,103.312904,219.096809
3,S04,1.0,0.0,pt,5750.000000,0.103743,0.107076,0.106194,,,,,,,0.03596,0.016435,0.009913,,,,,,,18550.296359,15231.07536,11185.774767,,,,,,,13.438899,12.800314,8.528069,,,,,,,5750.550381,5750.550381,5750.550381,,,,,,,104.057411,103.448224,96.625126,,,,,,,9268.764887,8021.454829,7279.460418,,,,,,,173.526595,174.54846,186.874045,,,,,,
4,S05,1.0,0.0,pt,5372.000000,0.106428,0.103779,0.109662,,,,,,,0.013317,0.009995,0.005318,,,,,,,13795.512278,10716.934801,7285.690093,,,,,,,19.972425,8.571825,8.611889,,,,,,,5368.839966,5368.839966,5368.839966,,,,,,,95.872463,95.976631,86.70923,,,,,,,7666.6358,7107.350129,6278.363827,,,,,,,175.839411,175.648565,194.421719,,,,,,
5,S06,1.0,0.0,pt,5804.000000,0.102041,0.102716,0.102248,,,,,,,0.010802,0.00821,0.009769,,,,,,,10712.785775,8576.037257,9999.15326,,,,,,,9.612124,9.810438,12.262222,,,,,,,5808.636749,5808.636749,5808.636749,,,,,,,110.161899,104.201227,103.432419,,,,,,,7280.09518,6869.146299,7196.536766,,,,,,,165.566494,175.037472,176.338517,,,,,,
6,S07,1.0,0.0,pt,5447.000000,0.117247,0.121782,,,,,,,,0.01334,0.007979,,,,,,,,15948.856901,11173.327688,,,,,,,,23.10515,13.044374,,,,,,,,5451.820491,5451.820491,,,,,,,,68.654684,67.570562,,,,,,,,8143.358876,7246.237426,,,,,,,,249.345205,253.345776,,,,,,,
7,S08,1.0,1.0,pt,3370.000000,0.150835,0.161233,0.144541,,,,,,,0.002789,0.002782,0.004641,,,,,,,7551.227773,7638.357324,10065.53768,,,,,,,10.234696,10.287005,9.030489,,,,,,,3339.96613,3339.96613,3339.96613,,,,,,,43.730744,42.526667,43.138527,,,,,,,5078.51954,5171.122317,5792.681481,,,,,,,239.819696,246.609816,243.112,,,,,,
8,S09,1.0,1.0,pt,3622.000000,0.14204,0.136088,0.133269,,,,,,,0.005419,0.00554,0.005293,,,,,,,10625.656224,9360.203218,9517.866215,,,,,,,10.273424,11.948557,21.313224,,,,,,,3622.099915,3622.099915,3622.099915,,,,,,,55.755492,55.517256,53.960332,,,,,,,5826.901464,5596.319438,5651.561697,,,,,,,203.986967,204.862316,210.773233,,,,,,
9,S10,1.0,0.0,pt,3115.000000,0.139613,0.143177,0.131833,,,,,,,0.007038,0.007549,0.007382,,,,,,,12857.832345,13214.648603,10521.930567,,,,,,,15.312898,16.150865,17.145273,,,,,,,3082.726503,3082.726503,3082.726503,,,,,,,51.011316,50.166816,55.983247,,,,,,,5975.269696,6066.656816,5823.560949,,,,,,,189.757137,192.951478,172.904606,,,,,,
10,S11,0.0,0.0,pl,2014.886014,0.10425,0.119245,0.095665,0.095566,0.122176,0.116533,0.100599,0.108498,0.093699,0.00587,0.006452,0.007453,0.004532,0.006173,0.0059,0.006881,0.022316,0.0059,6605.249788,8621.676545,7903.895004,6099.068586,12837.087214,7638.357324,6538.865368,17060.795936,5866.723116,12.176044,10.613703,16.66669,11.456381,13.129172,15.512696,7.676709,19.708781,9.113271,4485.097375,2348.348857,4485.097375,4485.097375,2348.348857,2348.348857,4485.097375,2348.348857,2348.348857,63.236134,35.206797,65.29981,63.833656,36.773212,47.940787,56.736038,29.790426,57.468531,5217.113024,5137.834911,5514.998015,5157.252595,5588.141712,5172.513087,5097.714628,6922.979348,4703.489921,222.708202,209.44295,215.669936,220.623519,200.521385,153.810897,248.223287,247.522991,128.31049
11,S12,0.0,0.0,pl,1531.468471,0.100455,0.116074,0.106657,0.132255,0.124468,0.142716,0.104147,0.094522,0.068557,0.011616,0.005616,0.012631,0.006446,0.013471,0.007241,0.011885,0.02666,0.030889,14318.289585,7966.130398,15488.314987,12907.62066,15276.714649,12762.404742,13152.413209,17708.04403,13106.77392,13.97852,5.951706,8.371173,11.776179,20.23763,13.037315,14.540281,17.304007,18.512992,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,57.517338,50.490533,46.14107,42.779974,45.962235,41.779624,53.020507,49.275712,60.084041,6190.11629,5114.221455,6283.44372,5552.158382,6341.669443,5480.466717,5875.951553,7308.047763,6248.771262,121.179969,138.044674,151.057381,162.925513,151.645132,166.826517,131.457612,141.447965,116.003335
12,S13,1.0,1.0,pl,2060.244079,0.102669,0.147456,0.094925,0.109437,0.125394,0.118772,0.109486,0.134071,0.092488,0.007487,0.006481,0.001893,0.006627,0.007379,0.011169,0.004062,0.004308,0.008113,13550.719729,13716.680779,4850.211685,10252.243861,11210.668925,11140.135478,5323.200677,10920.237087,9235.73243,32.698047,17.735567,22.369521,29.104753,15.513014,17.8851,12.150716,11.810321,15.749991,2402.286198,2402.286198,4592.972058,2402.286198,2402.286198,2402.286198,2402.286198,2402.286198,2070.364098,41.447797,41.789584,53.638975,48.615728,51.771745,46.529697,44.006336,42.939184,47.791097,5590.773533,5725.229728,4822.739894,5662.294952,5636.014397,5848.041721,4428.071705,5192.085589,5422.509498,181.992272,180.503799,268.870395,155.159225,145.700684,162.115362,171.411195,175.671214,136.028332
13,S14,1.0,0.0,pl,3058.309851,0.113748,0.155692,0.108589,0.148485,0.149526,0.120295,0.105627,0.162624,0.122447,0.005138,0.005589,0.005108,0.003549,0.004283,0.004969,0.002456,0.002549,0.027893,7808.467401,12886.875529,8837.42591,8787.637595,10455.546147,7625.910246,6588.653683,6717.273497,18541.998307,25.539034,14.402887,11.473142,14.388196,11.455092,19.340598,13.399599,6.989989,15.354504,3617.950889,3617.950889,3617.950889,3617.950889,3617.950889,3617.950889,3617.950889,3617.950889,3066.130398,41.828876,44.444487,40.877982,44.034305,43.510702,48.552634,42.233956,41.369253,41.985465,5637.890669,6119.027133,5559.983572,5598.390402,5806.685858,5918.771637,4941.75072,5147.659775,8011.400627,271.591468,255.607986,277.909166,257.988985,261.093599,233.980424,268.986542,274.608916,229.309107
14,S15,1.0,1.0,pl,2825.273540,0.112983,0.147976,0.109003,0.115212,0.142412,0.12917,0.117977,0.142653,0.1146,0.002165,0.003642,0.01038,0.005803,0.023006,0.00756,0.006217,0.004652,0.001999,6397.798476,9617.442845,9596.697714,8683.911939,18537.84928,11579.932261,7480.694327,8368.585944,6526.41829,12.70381,16.358749,8.391772,11.061809,17.509511,16.798596,6.911676,10.550343,13.066533,3310.922947,3310.922947,3310.922947,3310.922947,3310.922947,3310.922947,2837.933954,3310.922947,2837.933954,43.756374,42.191975,43.705062,47.092386,44.280407,42.86763,40.395283,43.657784,38.609247,4888.922728,5413.182118,5475.279215,5602.58452,8246.671452,5950.083269,4975.770911,5365.793114,4907.044778,237.595054,246.404634,237.874004,220.763885,234.783256,242.52094,220.597853,238.131601,230.802549
15,S16,0.0,0.0,pt,4472.000000,0.094983,0.103072,0.095272,,,,,,,0.03421,0.030737,0.074818,,,,,,,18147.840813,17994.326842,19093.818798,,,,,,,20.406481,27.151993,27.413262,,,,,,,4476.799323,4468.50127,4468.50127,,,,,,,106.622116,116.556114,128.154731,,,,,,,8243.048705,8179.077191,9401.664029,,,,,,,131.840845,120.380592,109.485572,,,,,,
16,S17,1.0,0.0,pt,4498.000000,0.138445,0.136462,0.133319,,,,,,,0.009528,0.006342,0.005917,,,,,,,15903.217612,10057.239627,9725.317528,,,,,,,14.53502,28.75912,13.660844,,,,,,,4497.544454,4497.544454,4501.69348,,,,,,,60.258058,61.271529,60.495405,,,,,,,7187.299313,6364.293998,6269.550554,,,,,,,234.363504,230.486978,233.659358,,,,,,
17,S18,1.0,1.0,pt,4719.000000,0.126957,0.125633,0.126339,,,,,,,0.013947,0.010877,0.01438,,,,,,,17110.584251,16114.817951,16608.552075,,,,,,,18.808423,19.82797,21.219746,,,,,,,4721.591871,4721.591871,4721.591871,,,,,,,67.868074,69.889158,65.695792,,,,,,,7774.523108,7321.516971,7871.221624,,,,,,,218.45026,212.133024,225.673486,,,,,,
18,S19,1.0,1.0,pt,4536.000000,0.130424,0.128729,0.128873,,,,,,,0.005106,0.006342,0.002796,,,,,,,8646.570703,9368.50127,5982.895851,,,,,,,10.644724,14.040388,8.113745,,,,,,,4522.438611,4522.438611,4522.438611,,,,,,,61.50226,63.023199,60.334882,,,,,,,6148.651569,6257.74,5380.478478,,,,,,,230.89326,225.321112,235.360651,,,,,,
19,S20,0.0,0.0,pt,4571.000000,0.131623,0.132341,0.13516,,,,,,,0.004457,0.006075,0.009662,,,,,,,8015.918713,9696.274344,14260.203218,,,,,,,7.596514,14.895237,10.995869,,,,,,,4580.524979,4580.524979,4580.524979,,,,,,,62.668975,62.197148,61.854314,,,,,,,6089.135049,6370.570835,7178.409083,,,,,,,229.505085,231.246108,232.527815,,,,,,
20,S21,1.0,1.0,pt,4823.929005,0.12705,0.122466,0.123538,,,,,,,0.005835,0.006418,0.006263,,,,,,,8580.186283,9248.179509,9517.866215,,,,,,,12.808549,15.508485,14.223432,,,,,,,4821.168501,4821.168501,4821.168501,,,,,,,70.954715,71.705148,69.956652,,,,,,,6257.254237,6420.425096,6495.697888,,,,,,,213.353956,211.121092,216.39785,,,,,,
21,S22,1.0,1.0,pt,6597.000000,0.113047,0.109769,0.109336,,,,,,,0.052445,0.019505,0.049594,,,,,,,19102.11685,16786.960203,19135.30906,,,,,,,22.906351,16.898246,13.081366,,,,,,,6601.100762,6601.100762,6601.100762,,,,,,,90.887183,88.762793,93.336582,,,,,,,10046.854175,9024.661848,10060.389593,,,,,,,228.05698,233.515144,222.07216,,,,,,
22,S23,1.0,1.0,pt,6197.000000,0.114594,0.117707,0.114964,,,,,,,0.004668,0.010289,0.00796,,,,,,,7547.078747,12326.756986,9629.889924,,,,,,,13.666892,13.69739,12.059372,,,,,,,6194.49619,6194.49619,6194.49619,,,,,,,81.761156,77.128605,85.403333,,,,,,,6717.067615,7890.172688,7339.27297,,,,,,,237.896808,252.185528,227.751277,,,,,,
23,S24,1.0,1.0,pt,6406.000000,0.114091,0.118094,0.114941,,,,,,,0.023389,0.007928,0.006525,,,,,,,17608.467401,10584.165961,8671.46486,,,,,,,15.435573,18.95926,14.716827,,,,,,,6410.245555,6406.096528,6406.096528,,,,,,,83.667337,80.818163,88.726083,,,,,,,9109.706964,7749.761926,7283.839112,,,,,,,240.573823,248.893841,226.710595,,,,,,
24,S25,0.0,0.0,pl,2384.185089,0.14302,0.174143,0.109386,0.150022,0.130951,0.124913,0.124554,0.122897,0.146903,0.018643,0.007926,0.022913,0.00206,0.007253,0.006325,0.006333,0.004118,0.002693,18210.076207,17450.804403,18264.013548,5804.487722,10501.185436,8642.421677,8638.27265,8198.475868,11036.409822,18.344333,8.993769,21.515236,12.250224,20.018154,11.144612,11.168882,15.732931,16.021912,2837.933954,2837.933954,2837.933954,2837.933954,2837.933954,2837.933954,2837.933954,2837.933954,2837.933954,34.289812,34.33738,42.814239,34.010678,39.9904,34.104253,34.477962,33.54653,28.427882,7939.21441,6984.448311,8232.37508,4747.030118,5887.287916,5505.890873,5504.511736,5330.057393,5448.704757,259.876392,259.516385,208.134321,262.009259,222.831296,261.290365,258.458219,265.634407,313.463819
25,S26,0.0,0.0,pl,3740.000000,0.115215,0.124276,0.088052,0.118328,,0.122534,0.112984,0.129852,0.105226,0.080425,0.048385,0.018376,0.045927,,0.012956,0.010283,0.010081,0.016101,19537.764606,19176.799323,12380.694327,19002.54022,,14886.706181,12181.541067,14953.090601,16338.865368,26.87823,14.891165,16.011248,19.775155,,17.318478,12.25552,14.846602,16.150298,3754.868755,5169.686706,3750.719729,5169.686706,,5169.686706,3750.719729,5165.53768,3754.868755,55.452848,68.567037,55.168118,60.961888,,59.379477,47.599912,71.497111,50.255225,10098.977903,9620.232941,7065.833979,9394.961832,,7540.034348,6585.525073,7339.605949,7351.529431,212.618257,236.743734,213.47946,266.27811,,273.374186,247.421885,226.859354,234.608199
26,S27,0.0,0.0,pt,9348.000000,0.099292,,0.094538,,,,,,,0.021149,,0.027828,,,,,,,15766.299746,,16438.441998,,,,,,,10.016974,,11.283894,,,,,,,9430.736664,,9430.736664,,,,,,,101.614609,,108.548707,,,,,,,10277.88575,,10153.656288,,,,,,,291.419841,,272.803923,,,,,,
27,S28,0.0,0.0,pt,8478.000000,0.107934,,,,,,,,,0.01574,,,,,,,,,14372.226926,,,,,,,,,9.728752,,,,,,,,,8937.00254,,,,,,,,,91.704182,,,,,,,,,9695.253407,,,,,,,,,306.007723,,,,,,,,
28,S29,,,pt,9207.000000,,0.092604,0.084747,,,,,,,,0.066821,0.024149,,,,,,,,18786.790855,15621.083827,,,,,,,,13.094887,16.838899,,,,,,,,9526.164268,9522.015241,,,,,,,,96.126802,121.38828,,,,,,,,10777.153133,10149.920388,,,,,,,,311.17394,246.30984,,,,,,
29,S30,1.0,1.0,pl,3271.000000,0.120115,0.165046,0.13148,0.163405,0.17257,0.146175,0.13003,0.18133,0.165057,0.015405,0.006395,0.124783,0.00573,0.004952,0.013006,0.003389,0.010797,0.005816,16807.705334,16521.422523,19894.580864,14239.458086,15421.930567,17529.635902,7447.502117,18064.860288,13629.551228,11.409059,10.920796,23.700935,13.110906,10.228563,10.58573,8.574294,14.671664,19.049389,3833.700254,3833.700254,3286.028789,3833.700254,3833.700254,3833.700254,3833.700254,3833.700254,3833.700254,30.790683,30.241608,32.068281,30.893915,31.06829,34.787812,29.374213,30.207505,27.291869,7621.196293,7087.67822,10923.688547,6852.673797,6743.112275,7997.508411,5574.91248,7957.830682,6589.373588,390.956532,398.054849,321.755025,389.650162,387.463191,346.035529,409.809069,398.504238,441.077116
30,S31,1.0,0.0,pl,3020.000000,0.155497,0.190644,0.127823,0.196311,0.186941,0.174533,0.129668,0.201567,0.157036,0.007652,0.002176,0.000994,0.001298,0.003788,0.003231,0.000583,0.002583,0.001897,15255.969517,8629.974598,6663.336156,5916.511431,13310.076207,9463.928874,6634.292972,8414.225233,5688.314987,12.606471,12.163533,8.684323,11.172595,16.549231,16.69908,20.38064,13.928079,6.550501,3456.138865,3456.138865,3451.989839,3456.138865,3456.138865,3456.138865,3451.989839,3456.138865,3451.989839,24.902175,25.407826,26.465602,25.914227,26.039233,26.775503,26.909441,24.830045,22.767452,6656.465406,5434.313215,4832.325351,4769.890972,6135.595823,5758.063079,4726.509981,5464.058606,4692.989267,435.796305,427.123353,409.55986,418.776762,416.766354,405.306146,402.804655,437.062279,476.085241

In [ ]:
stats = out.copy()

# Pop column in string format
sample_name = stats.pop('sample_name')
form_1 = stats.pop('form_1')

# Convert other columns in float
stats = stats.apply(pd.to_numeric)

# Compute stats (mean, std, min, max) for each features

rms_columns = ['rms_1', 'rms_2', 'rms_3', 'rms_4', 'rms_5', 'rms_6', 'rms_7', 'rms_8', 'rms_9']
stats['rms_mean'] = stats[rms_columns].mean(axis=1)
stats['rms_std'] = stats[rms_columns].std(axis=1)
stats['rms_min'] = stats[rms_columns].min(axis=1)
stats['rms_max'] = stats[rms_columns].max(axis=1)

flatness_columns = ['flatness_1', 'flatness_2', 'flatness_3', 'flatness_4', 'flatness_5', 'flatness_6', 'flatness_7', 'flatness_8', 'flatness_9']
stats['flatness_mean'] = stats[flatness_columns].mean(axis=1)
stats['flatness_std'] = stats[flatness_columns].std(axis=1)
stats['flatness_min'] = stats[flatness_columns].min(axis=1)
stats['flatness_max'] = stats[flatness_columns].max(axis=1)

rolloff_columns = ['rolloff_1', 'rolloff_2', 'rolloff_3', 'rolloff_4', 'rolloff_5', 'rolloff_6', 'rolloff_7', 'rolloff_8', 'rolloff_9']
stats['rolloff_mean'] = stats[rolloff_columns].mean(axis=1)
stats['rolloff_std'] = stats[rolloff_columns].std(axis=1)
stats['rolloff_min'] = stats[rolloff_columns].min(axis=1)
stats['rolloff_max'] = stats[rolloff_columns].max(axis=1)

contrast_columns = ['contrast_1', 'contrast_2', 'contrast_3', 'contrast_4', 'contrast_5', 'contrast_6', 'contrast_7', 'contrast_8', 'contrast_9']
stats['contrast_mean'] = stats[contrast_columns].mean(axis=1)
stats['contrast_std'] = stats[contrast_columns].std(axis=1)
stats['contrast_min'] = stats[contrast_columns].min(axis=1)
stats['contrast_max'] = stats[contrast_columns].max(axis=1)

f1_audio_columns = ['f1_audio_1', 'f1_audio_2', 'f1_audio_3', 'f1_audio_4', 'f1_audio_5', 'f1_audio_6', 'f1_audio_7', 'f1_audio_8', 'f1_audio_9']
stats['f1_audio_mean'] = stats[f1_audio_columns].mean(axis=1)
stats['f1_audio_std'] = stats[f1_audio_columns].std(axis=1)
stats['f1_audio_min'] = stats[f1_audio_columns].min(axis=1)
stats['f1_audio_max'] = stats[f1_audio_columns].max(axis=1)

centroid_columns = ['centroid_1', 'centroid_2', 'centroid_3', 'centroid_4', 'centroid_5', 'centroid_6', 'centroid_7', 'centroid_8', 'centroid_9']
stats['centroid_mean'] = stats[centroid_columns].mean(axis=1)
stats['centroid_std'] = stats[centroid_columns].std(axis=1)
stats['centroid_min'] = stats[centroid_columns].min(axis=1)
stats['centroid_max'] = stats[centroid_columns].max(axis=1)

c_columns = ['c_1', 'c_2', 'c_3', 'c_4', 'c_5', 'c_6', 'c_7', 'c_8', 'c_9']
stats['c_mean'] = stats[c_columns].mean(axis=1)
stats['c_std'] = stats[c_columns].std(axis=1)
stats['c_min'] = stats[c_columns].min(axis=1)
stats['c_max'] = stats[c_columns].max(axis=1)

Q_columns = ['Q_1', 'Q_2', 'Q_3', 'Q_4', 'Q_5', 'Q_6', 'Q_7', 'Q_8', 'Q_9']
stats['Q_mean'] = stats[Q_columns].mean(axis=1)
stats['Q_std'] = stats[Q_columns].std(axis=1)
stats['Q_min'] = stats[Q_columns].min(axis=1)
stats['Q_max'] = stats[Q_columns].max(axis=1)


#out[rms_columns].dtypes

stats.insert(0, 'form_1', form_1)
stats.insert(0, 'sample_name', sample_name)


stats

,sample_name,form_1,frost_resitant_01,frost_resitant_001,f1_vibration,rms_1,rms_2,rms_3,rms_4,rms_5,rms_6,rms_7,rms_8,rms_9,flatness_1,flatness_2,flatness_3,flatness_4,flatness_5,flatness_6,flatness_7,flatness_8,flatness_9,rolloff_1,rolloff_2,rolloff_3,rolloff_4,rolloff_5,rolloff_6,rolloff_7,rolloff_8,rolloff_9,contrast_1,contrast_2,contrast_3,contrast_4,contrast_5,contrast_6,contrast_7,contrast_8,contrast_9,f1_audio_1,f1_audio_2,f1_audio_3,f1_audio_4,f1_audio_5,f1_audio_6,f1_audio_7,f1_audio_8,f1_audio_9,c_1,c_2,c_3,c_4,c_5,c_6,c_7,c_8,c_9,centroid_1,centroid_2,centroid_3,centroid_4,centroid_5,centroid_6,centroid_7,centroid_8,centroid_9,Q_1,Q_2,Q_3,Q_4,Q_5,Q_6,Q_7,Q_8,Q_9,rms_mean,rms_std,rms_min,rms_max,flatness_mean,flatness_std,flatness_min,flatness_max,rolloff_mean,rolloff_std,rolloff_min,rolloff_max,contrast_mean,contrast_std,contrast_min,contrast_max,f1_audio_mean,f1_audio_std,f1_audio_min,f1_audio_max,centroid_mean,centroid_std,centroid_min,centroid_max,c_mean,c_std,c_min,c_max,Q_mean,Q_std,Q_min,Q_max
0,S01,pl,1.0,0.0,2748.000000,0.122204,0.129421,0.111234,0.128124,0.130879,0.114371,0.101053,0.122191,0.103574,0.008963,0.007643,0.012436,0.008403,0.013390,0.014131,0.012329,0.007448,0.002556,12397.290432,14052.751905,16177.053345,13538.272650,16525.571550,14973.835732,10887.044877,10633.954276,6397.798476,14.673802,10.566528,12.863068,14.208599,19.863773,13.529413,13.348872,16.384968,15.057705,3223.793395,3227.942422,3223.793395,3227.942422,3227.942422,3227.942422,3223.793395,3223.793395,3223.793395,55.140871,59.485896,57.890860,63.182687,60.316329,66.255863,59.274832,64.133336,58.612620,5841.668799,6028.623430,6446.748089,6010.692139,6893.026751,6581.526085,5742.024542,5688.223022,4881.061628,183.579095,170.388946,174.858539,160.419565,168.043038,152.978751,170.775874,157.838526,172.705320,0.118117,0.011114,0.101053,0.130879,0.009700,0.003712,0.002556,0.014131,12842.619249,3193.930404,6397.798476,16525.571550,14.499636,2.577989,10.566528,19.863773,3225.637407,2.186729e+00,3223.793395,3227.942422,6012.621609,589.024741,4881.061628,6893.026751,60.477033,3.449210,55.140871,66.255863,167.954184,9.431595,152.978751,183.579095
1,S02,pl,1.0,0.0,3289.000000,0.118736,0.145612,0.109484,0.137154,0.138425,0.132420,0.109408,0.147778,0.134464,0.016339,0.015454,0.006394,0.015358,0.027054,0.011955,0.006970,0.007724,0.006021,18280.609653,18268.162574,10787.468247,17600.169348,18741.151566,16089.923793,8679.762913,16152.159187,10376.714649,29.826742,18.819980,18.723538,18.685090,30.014621,17.509814,11.260597,20.458865,12.831292,3315.071973,3593.056732,3315.071973,3593.056732,3593.056732,3593.056732,3315.071973,3593.056732,3315.071973,53.590213,55.768092,52.344184,52.534777,56.854063,54.397365,52.550665,48.540497,56.479053,7814.978773,7963.651772,5625.709233,7481.775787,8567.668763,7020.566623,5358.211364,6684.951085,5688.567321,194.239311,202.305613,198.863085,214.756752,198.441371,207.403396,198.081716,232.428568,184.304188,0.130387,0.014484,0.109408,0.147778,0.012585,0.006859,0.006021,0.027054,14997.346881,3933.530719,8679.762913,18741.151566,19.792282,6.474943,11.260597,30.014621,3469.507950,1.465108e+02,3315.071973,3593.056732,6911.786747,1151.963200,5358.211364,8567.668763,53.673212,2.587895,48.540497,56.854063,203.424889,13.742620,184.304188,232.428568
2,S03,pl,1.0,0.0,1665.211513,0.105056,0.118863,0.093317,0.106551,0.100342,0.093870,0.106784,0.085500,0.091838,0.009940,0.009023,0.006666,0.006019,0.006953,0.002398,0.012777,0.012875,0.005959,13911.685013,15558.848434,6837.595258,6879.085521,7609.314141,4742.337003,16214.394581,13650.296359,5895.766300,15.193014,17.114730,14.292372,10.734138,21.940421,8.499996,14.247616,17.561312,5.571778,3900.084674,1788.230313,3900.084674,3900.084674,1788.230313,3900.084674,1788.230313,1788.230313,3895.935648,56.806662,44.974850,59.088341,51.434448,58.481212,62.897749,44.583643,54.349873,55.834852,6197.090933,5959.802284,5035.394561,5013.249370,5459.173114,4558.928434,6193.474734,6016.156455,4705.888714,215.577989,124.848513,207.253506,238.094629,96.014480,194.701178,125.944018,103.312904,219.096809,0.100236,0.010180,0.085500,0.118863,0.008068,0.003422,0.002398,0.012875,10144.369179,4581.237568,4742.337003,16214.394581,13.906153,4.985935,5.571778,21.940421,2961.021733,1.112608e+03,1788.230313,3900.084674,5459.906511,652.005642,4558.928434,6197.090933,54.272403,6.250442,44.583643,62.897749,169.427114,55.924457,96.014480,238.094629
3,S04,pt,1.0,0.0,5750.000000,0.103743,0.107076,0.106194,NaN,NaN,NaN,NaN,NaN,NaN,0.035960,0.016435,0.009913,NaN,NaN,NaN,NaN,NaN,NaN,18550.296359,15231.075360,11185.774767,NaN,NaN,NaN,NaN,NaN,NaN,13.438899,12.800314,8.528069,NaN,NaN,NaN,NaN,NaN,NaN,5750.550381,5750.550381,5750.550381,NaN,NaN,NaN,NaN,NaN,NaN,104.057411,103.448224,96.625126,NaN,NaN,NaN,NaN,NaN,NaN,9268.764887,8021.454829,7279.460418,NaN,NaN,NaN,NaN,NaN,NaN,173.526595,174.548460,186.874045,NaN,NaN,NaN,NaN,NaN,NaN,0.105671,0.001727,0.103743,0.107076,0.020769,0.013554,0.009913,0.035960,14989.048829,3688.221414,11185.774767,18550.296359,11.589094,2.670085,8.528069,13.438899,5750.550381,0.000000e+00,5750.550381,5750.550381,8189.893378,1005.291861,7279.460418,9268.764887,101.376921,4.126432,96.625126,104.057411,178.316366,7.428758,173.526595,186.874045
4,S05,pt,1.0,0.0,5372.000000,0.106428,0.103779,0.109662,NaN,NaN,NaN,NaN,NaN,NaN,0.013317,0.009995,0.005318,NaN,NaN,NaN,NaN,NaN,NaN,13795.512278,10716.934801,7285.690093,NaN,NaN,NaN,NaN,NaN,NaN,19.972425,8.571825,8.611889,NaN,NaN,NaN,NaN,NaN,NaN,5368.839966,5368.839966,5368.839966,NaN,NaN,NaN,NaN,NaN,NaN,95.872463,95.976631,86.709230,NaN,NaN,NaN,NaN,NaN,NaN,7666.635800,7107.350129,6278.363827,NaN,NaN,NaN,NaN,NaN,NaN,175.839411,175.648565,194.421719,NaN,NaN,NaN,NaN,NaN,NaN,0.106623,0.002947,0.103779,0.109662,0.009543,0.004019,0.005318,0.013317,10599.379057,3256.502838,7285.690093,13795.512278,12.385380,6.570605,8.571825,19.972425,5368.839966,0.000000e+00,5368.839966,5368.839966,7017.449919,698.488585,6278.363827,7666.635800,92.852775,5.320721,86.709230,95.976631,181.969898,10.784015,175.648565,194.421719
5,S06,pt,1.0,0.0,5804.000000,0.102041,0.102716,0.102248,NaN,NaN,NaN,NaN,NaN,NaN,0.010802,0.008210,0.009769,NaN,NaN,NaN,NaN,NaN,NaN,10712.785775,8576.037257,9999.153260,NaN,NaN,NaN,NaN,NaN,NaN,9.612124,9.810438,12.262222,NaN,NaN,NaN,NaN,NaN,NaN,5808.636749,5808.636749,5808.636749,NaN,NaN,NaN,NaN,NaN,NaN,110.161899,104.201227,103.432419,NaN,NaN,NaN,NaN,NaN,NaN,7280.095180,6869.146299,7196.536766,NaN,NaN,NaN,NaN,NaN,NaN,165.566494,175.037472,176.338517,NaN,NaN,NaN,NaN,NaN,NaN,0.102335,0.000346,0.102041,0.102716,0.009594,0.001305,0.008210,0.010802,9762.658764,1087.828476,8576.037257,10712.785775,10.561595,1.476121,9.612124,12.262222,5808.636749,0.000000e+00,5808.636749,5808.636749,7115.259415,217.196343,6869.146299,7280.095180,105.931849,3.683444,103.432419,110.161899,172.314161,5.879748,165.566494,176.338517
6,S07,pt,1.0,0.0,5447.000000,0.117247,0.121782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.013340,0.007979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15948.856901,11173.327688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.105150,13.044374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5451.820491,5451.820491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.654684,67.570562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8143.358876,7246.237426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249.345205,253.345776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.119514,0.003207,0.117247,0.121782,0.010660,0.003791,0.007979,0.013340,13561.092295,3376.809090,11173.327688,15948.856901,18.074762,7.114043,13.044374,23.105150,5451.820491,0.000000e+00,5451.820491,5451.820491,7694.798151,634.360661,7246.237426,8143.358876,68.112623,0.766591,67.570562,68.654684,251.345491,2.828831,249.345205,253.345776
7,S08,pt,1.0,1.0,3370.000000,0.150835,0.161233,0.144541,NaN,NaN,NaN,NaN,NaN,NaN,0.002789,0.002782,0.004641,NaN,NaN,NaN,NaN,NaN,NaN,7551.227773,7638.357324,10065.537680,NaN,NaN,NaN,NaN,NaN,NaN,10.234696,10.287005,9.030489,NaN,NaN,NaN,NaN,NaN,NaN,3339.966130,3339.966130,3339.966130,NaN,NaN,NaN,NaN,NaN,NaN,43.730744,42.526667,43.138527,NaN,NaN,NaN,NaN,NaN,NaN,5078.519540,5171.122317,5792.681481,NaN,NaN,NaN,NaN,NaN,NaN,239.819696,246.609816,243.112000,NaN,NaN,NaN,NaN,NaN,NaN,0.152203,0.008430,0.144541,0.161233,0.003404,0.001071,0.002782,0.004641,8418.374259,1427.150444,7551.227773,10065.537680,9.850730,0.710831,9.030489,10.287005,3339.966130,0.000000e+00,3339.966130,3339.966130,5347.441113,388.359444,5078.519540,5792.681481,43.131979,0.602065,42.526667,43.730744,243.180504,3.395579,239.819696,246.609816
8,S09,pt,1.0,1.0,3622.000000,0.142040,0.136088,0.133269,NaN,NaN,NaN,NaN,NaN,NaN,0.005419,0.005540,0.005293,NaN,NaN,NaN,NaN,NaN,NaN,10625.656224,9360.203218,9517.866215,NaN,NaN,NaN,NaN,NaN,NaN,10.273424,11.948557,21.313224,NaN,NaN,NaN,NaN,NaN,NaN,3622.099915,3622.099915,3622.099915,NaN,NaN,NaN,NaN,NaN,NaN,55.755492,55.517256,53.960332,NaN,NaN,NaN,NaN,NaN,NaN,5826.901464,5596.319438,5651.561697,NaN,NaN,NaN,NaN,NaN,NaN,203.986967,204.862316,210.773233,NaN,NaN,NaN,NaN,NaN,NaN,0.137133,0.004478,0.133269,0.142040,0.005417,0.000123,0.005293,0.005540,9834.575219,689.616758,9360.203218,10625.656224,14.511735,5.949513,10.273424,21.313224,3622.099915,0.000000e+00,3622.099915,3622.099915,5691.594200,120.390900,5596.319438,5826.901464,55.077694,0.974967,53.960332,55.755492,206.540839,3.691400,203.986967,210.773233
9,S10,pt,1.0,0.0,3115.000000,0.139613,0.143177,0.131833,NaN,NaN,NaN,NaN,NaN,NaN,0.007038,0.007549,0.007382,NaN,NaN,NaN,NaN,NaN,NaN,12857.832345,13214.648603,10521.930567,NaN,NaN,NaN,NaN,NaN,NaN,15.312898,16.150865,17.145273,NaN,NaN,NaN,NaN,NaN,NaN,3082.726503,3082.726503,3082.726503,NaN,NaN,NaN,NaN,NaN,NaN,51.011316,50.166816,55.983247,NaN,NaN,NaN,NaN,NaN,NaN,5975.269696,6066.656816,5823.560949,NaN,NaN,NaN,NaN,NaN,NaN,189.757137,192.951478,172.904606,NaN,NaN,NaN,NaN,NaN,NaN,0.138208,0.005801,0.131833,0.143177,0.007323,0.000261,0.007038,0.007549,12198.137172,1462.559707,10521.930567,13214.648603,16.203012,0.917300,15.312898,17.145273,3082.726503,5.569495e-13,3082.726503,3082.726503,5955.162487,122.788945,5823.560949,6066.656816,52.387126,3.142826,50.166816,55.983247,185.204407,10.771016,172.904606,192.951478
10,S11,pl,0.0,0.0,2014.886014,0.104250,0.119245,0.095665,0.095566,0.122176,0.116533,0.100599,0.108498,0.093699,0.005870,0.006452,0.007453,0.004532,0.006173,0.005900,0.006881,0.022316,0.005900,6605.249788,8621.676545,7903.895004,6099.068586,12837.087214,7638.357324,6538.865368,17060.795936,5866.723116,12.176044,10.613703,16.666690,11.456381,13.129172,15.512696,7.676709,19.708781,9.113271,4485.097375,2348.348857,4485.097375,4485.097375,2348.348857,2348.348857,4485.097375,2348.348857,2348.348857,63.236134,35.206797,65.299810,63.833656,36.773212,47.940787,56.736038,29.790426,57.468531,5217.113024,5137.834911,5514.998015,5157.252595,5588.141712,5172.513087,5097.714628,6922.979348,4703.489921,222.708202,209.442950,215.669936,220.623519,200.521385,153.810897,248.223287,247.522991,128.310490,0.106248,0.010914,0.093699,0.122176,0.007942,0.005450,0.004532,0.022316,8796.857654,3750.862451,5866.723116,17060.795936,12.894827,3.822357,7.676709,19.708781,3298.014865,1.126165e+03,2348.348857,4485.097375,5390.226360,628.150633,4703.489921,6922.979348,50.698377,13.710703,29.790426,65.299810,205.203740,40.138836,128.310490,248.223287
11,S12,pl,0.0,0.0,1531.468471,0.100455,0.116074,0.106657,0.132255,0.124468,0.142716,0.104147,0.094522,0.068557,0.011616,0.005616,0.012631,0.006446,0.013471,0.007241,0.011885,0.026660,0.030889,14318.289585,7966.130398,15488.314987,12907.620660,15276.714649,12762.404742,13152.413209,17708.044030,13106.773920,13.978520,5.951706,8.371173,11.776179,20.237630,13.037315,14.540281,17.304007,18.512992,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,2219.729043,57.517338,50.490533,46.141070,42.779974,45.962235,41.779624,53.020507,49.275712,60.084041,6190.116290,5114.221455,6283.443720,5552.158382,6341.669443,5480.466717,5875.951553,7308.047763,6248.771262,121.179969,138.044674,151.057381,162.925513,151.645132,166.826517,131.457612,141.447965,116.003335,0.109983,0.022095,0.068557,0.142716,0.014050,0.008880,0.005616,0.030889,13631.856242,2672.194449,7966.130398,17708.044030,13.745534,4.639936,5.951706,20.237630,2219.729043,0.000000e+00,2219.729043,2219.729043,6043.871843,638.283302,5114.221455,7308.047763,49.672337,6.304948,41.779624,60.084041,142.287566,17.553294,116.003335,166.826517
12,S13,pl,1.0,1.0,2060.244079,0.102669,0.147456,0.094925,0.109437,0.125394,0.118772,0.109486,0.134071,0.092488,0.007487,0.006481,0.001893,0.006627,0.007379,0.011169,0.004062,0.004308,0.008113,13550.719729,13716.680779,4850.211685,10252.243861,11210.668925,11140.135478,5323.200677,10920.237087,9235.732430,32.698047,17.735567,22.369521,29.104753,15.513014,17.885100,12.150716,11.810321,15.749991,2402.286198,2402.286198,4592.972058,2402.286198,2402.286198,2402.286198,2402.286198,2402.286198,2070.364098,41.447797,41.789584,53.638975,48.615728,51.771745,46.529697,44.006336,42.939184,47.791097,5590.773533,5725.229728,4822.739894,5662.294952,5636.014397,5848.041721,4428.071705,5192.085589,5422.509498,181.992272,180.503799,268.870395,155.159225,145.700684,162.115362,171.411195,175.671214,136.028332,0.114966,0.018243,0.092488,0.147456,0.006391,0.002693,0.001893,0.011169,10022.203406,3143.840359,4850.211685,13716.680779,19.446337,7.275566,11.810321,32.698047,2608.815505,7.521127e+02,2070.364098,4592.972058,5369.751224,471.803159,4428.071705,5848.041721,46.503349,4.351879,41.447797,53.638975,175.272498,38.471430,136.028332,268.870395
13,S14,pl,1.0,0.0,3058.309851,0.113748,0.155692,0.108589,0.148485,0.149526,0.120295,0.105627,0.162624,0.122447,0.005138,0.005589,0.005108,0.003549,0.004283,0.004969,0.002456,0.002549,0.027893,7808.467401,12886.875529,8837.425910,8787.637595,10455.546147,7625.910246,6588.653683,6717.273497,18541.998307,25.539034,14.402887,11.473142,14.388196,11.455092,19.340598,13.399599,6.989989,15.354504,3617.950889,3617.950889,3617.950889,3617.950889,3617.950889,3617.950889,3617.950889,3617.950889,3066.130398,41.828876,44.444487,40.877982,44.034305,43.510702,48.552634,42.233956,41.369253,41.985465,5637.890669,6119.027133,5559.983572,5598.390402,5806.685858,5918.771637,4941.750720,5147.659775,8011.400627,271.591468,255.607986,277.909166,257.988985,261.093599,233.980424,268.986542,274.608916,229.309107,0.131893,0.022031,0.105627,0.162624,0.006837,0.007978,0.002456,0.027893,9805.532035,3821.665916,6588.653683,18541.998307,14.704782,5.264395,6.989989,25.539034,3556.637501,1.839402e+02,3066.130398,3617.950889,5860.173377,884.612081,4941.750720,8011.400627,43.204184,2.345837,40.877982,48.552634,259.008466,17.262349,229.309107,277.909166
14,S15,pl,1.0,1.0,2825.273540,0.112983,0.147976,0.109003,0.115212,0.142412,0.129170,0.117977,0.142653,0.114600,0.002165,0.003642,0.010380,0.005803,0.023006,0.007560,0.006217,0.004652,0.001999,6397.798476,9617.442845,9596.697714,8683.911939,18537.849280,11579.932261,7480.694327,8368.585944,6526.418290,12.703810,16.358749,8.391772,11.061809,17.509511,16.798596,6.911676,10.550343,13.066533,3310.922947,3310.922947,3310.922947,3310.922947,3310.922947,3310.922947,2837.933954,3310.922947,2837.933954,43.756374,42.191975,43.705062,47.092386,44.280407,42.867630,40.395283,43.657784,38.609247,4888.922728,5413.182118,5475.279215,5602.584520,8246.671452,5950.083269,4975.770911,5365.793114,4907.044778,237.595054,246.404634,237.874004,220.763885,234.783256,242.520940,220.597853,238.131601,230.802549,0.125776,0.015034,0.109003,0.147976,0.007269,0.006466,0.001999,0.023006,9643.259008,3713.771805,6397.798476,18537.849280,12.594756,3.753685,6.911676,17.509511,3205.814282,2.085685e+02,2837.933954,3310.922947,5647.259123,1036.105857,4888.922728,8246.671452,42.950683,2.413523,38.609247,47.092386,234.385975,8.914822,220.597853,246.404634
15,S16,pt,0.0,0.0,4472.000000,0.094983,0.103072,0.095272,NaN,NaN,NaN,NaN,NaN,NaN,0.034210,0.030737,0.074818,NaN,NaN,NaN,NaN,NaN,NaN,18147.840813,17994.326842,19093.818798,NaN,NaN,NaN,NaN,NaN,NaN,20.406481,27.151993,27.413262,NaN,NaN,NaN,NaN,NaN,NaN,4476.799323,4468.501270,4468.501270,NaN,NaN,NaN,NaN,NaN,NaN,106.622116,116.556114,128.154731,NaN,NaN,NaN,NaN,NaN,NaN,8243.048705,8179.077191,9401.664029,NaN,NaN,NaN,NaN,NaN,NaN,131.840845,120.380592,109.485572,NaN,NaN,NaN,NaN,NaN,NaN,0.097776,0.004589,0.094983,0.103072,0.046588,0.024509,0.030737,0.074818,18411.995484,595.444295,17994.326842,19093.818798,24.990579,3.972094,20.406481,27.413262,4471.267288,4.790883e+00,4468.501270,4476.799323,8607.929975,688.137631,8179.077191,9401.664029,117.110987,10.777026,106.622116,128.154731,120.569003,11.178828,109.485572,131.840845
16,S17,pt,1.0,0.0,4498.000000,0.138445,0.136462,0.133319,NaN,NaN,NaN,NaN,NaN,NaN,0.009528,0.006342,0.005917,NaN,NaN,NaN,NaN,NaN,NaN,15903.217612,10057.239627,9725.317528,NaN,NaN,NaN,NaN,NaN,NaN,14.535020,28.759120,13.660844,NaN,NaN,NaN,NaN,NaN,NaN,4497.544454,4497.544454,4501.693480,NaN,NaN,NaN,NaN,NaN,NaN,60.258058,61.271529,60.495405,NaN,NaN,NaN,NaN,NaN,NaN,7187.299313,6364.293998,6269.550554,NaN,NaN,NaN,NaN,NaN,NaN,234.363504,230.486978,233.659358,NaN,NaN,NaN,NaN,NaN,NaN,0.136075,0.002585,0.133319,0.138445,0.007262,0.001974,0.005917,0.009528,11895.258256,3474.959960,9725.317528,15903.217612,18.984994,8.475918,13.660844,28.759120,4498.927463,2.395441e+00,4497.544454,4501.693480,6607.047955,504.740338,6269.550554,7187.299313,60.674997,0.530067,60.258058,61.271529,232.836613,2.065077,230.486978,234.363504
17,S18,pt,1.0,1.0,4719.000000,0.126957,0.125633,0.126339,NaN,NaN,NaN,NaN,NaN,NaN,0.013947,0.010877,0.014380,NaN,NaN,NaN,NaN,NaN,NaN,17110.584251,16114.817951,16608.552075,NaN,NaN,NaN,NaN,NaN,NaN,18.808423,19.827970,21.219746,NaN,NaN,NaN,NaN,NaN,NaN,4721.591871,4721.591871,4721.591871,NaN,NaN,NaN,NaN,NaN,NaN,67.868074,69.889158,65.695792,NaN,NaN,NaN,NaN,NaN,NaN,7774.523108,7321.516971,7871.221624,NaN,NaN,NaN,NaN,NaN,NaN,218.450260,212.133024,225.673486,NaN,NaN,NaN,NaN,NaN,NaN,0.126310,0.000662,0.125633,0.126957,0.013068,0.001909,0.010877,0.014380,16611.318092,497.888912,16114.817951,17110.584251,19.952046,1.210440,18.808423,21.219746,4721.591871,0.000000e+00,4721.591871,4721.591871,7655.753901,293.467877,7321.516971,7871.221624,67.817675,2.097137,65.695792,69.889158,218.752256,6.775281,212.133024,225.673486
18,S19,pt,1.0,1.0,4536.000000,0.130424,0.128729,0.128873,NaN,NaN,NaN,NaN,NaN,NaN,0.005106,0.006342,0.002796,NaN,NaN,NaN,NaN,NaN,NaN,8646.570703,9368.501270,5982.895851,NaN,NaN,NaN,NaN,NaN,NaN,10.644724,14.040388,8.113745,NaN,NaN,NaN,NaN,NaN,NaN,4522.438611,4522.438611,4522.438611,NaN,NaN,NaN,NaN,NaN,NaN,61.502260,63.023199,60.334882,NaN,NaN,NaN,NaN,NaN,NaN,6148.651569,6257.740000,5380.478478,NaN,NaN,NaN,NaN,NaN,NaN,230.893260,225.321112,235.360651,NaN,NaN,NaN,NaN,NaN,NaN,0.129342,0.000940,0.128729,0.130424,0.004748,0.001800,0.002796,0.006342,7999.322608,1783.193367,5982.895851,9368.501270,10.932952,2.973816,8.113745,14.040388,4522.438611,0.000000e+00,4522.438611,4522.438611,5928.956682,478.117482,5380.478478,6257.740000,61.620114,1.348028,60.334882,63.023199,230.525008,5.029890,225.321112,235.360651
19,S20,pt,0.0,0.0,4571.000000,0.131623,0.132341,0.135160,NaN,NaN,NaN,NaN,NaN,NaN,0.004457,0.006075,0.009662,NaN,NaN,NaN,NaN,NaN,NaN,8015.918713,9696.274344,14260.203218,NaN,NaN,NaN,NaN,NaN,NaN,7.596514,14.895237,10.995869,NaN,NaN,NaN,NaN,NaN,NaN,4580.524979,4580.524979,4580.524979,NaN,NaN,NaN,NaN,NaN,NaN,62.668975,62.197148,61.854314,NaN,NaN,NaN,NaN,NaN,NaN,6089.135049,6370.570835,7178.409083,NaN,NaN,NaN,NaN,NaN,NaN,229.505085,231.246108,232.527815,NaN,NaN,NaN,NaN,NaN,NaN,0.133041,0.001869,0.131623,0.135160,0.006731,0.002664,0.004457,0.009662,10657.465425,3231.205420,8015.918713,14260.203218,11.162540,3.652215,7.596514,14.895237,4580.524979,0.000000e+00,4580.524979,4580.524979,6546.038322,565.438865,6089.135049,7178.409083,62.240146,0.409029,61.854314,62.668975,231.093003,1.517170,229.505085,232.527815

In [ ]:
print(list(stats.columns.values))

['sample_name', 'form_1', 'frost_resitant_01', 'frost_resitant_001', 'f1_vibration', 'rms_1', 'rms_2', 'rms_3', 'rms_4', 'rms_5', 'rms_6', 'rms_7', 'rms_8', 'rms_9', 'flatness_1', 'flatness_2', 'flatness_3', 'flatness_4', 'flatness_5', 'flatness_6', 'flatness_7', 'flatness_8', 'flatness_9', 'rolloff_1', 'rolloff_2', 'rolloff_3', 'rolloff_4', 'rolloff_5', 'rolloff_6', 'rolloff_7', 'rolloff_8', 'rolloff_9', 'contrast_1', 'contrast_2', 'contrast_3', 'contrast_4', 'contrast_5', 'contrast_6', 'contrast_7', 'contrast_8', 'contrast_9', 'f1_audio_1', 'f1_audio_2', 'f1_audio_3', 'f1_audio_4', 'f1_audio_5', 'f1_audio_6', 'f1_audio_7', 'f1_audio_8', 'f1_audio_9', 'c_1', 'c_2', 'c_3', 'c_4', 'c_5', 'c_6', 'c_7', 'c_8', 'c_9', 'centroid_1', 'centroid_2', 'centroid_3', 'centroid_4', 'centroid_5', 'centroid_6', 'centroid_7', 'centroid_8', 'centroid_9', 'Q_1', 'Q_2', 'Q_3', 'Q_4', 'Q_5', 'Q_6', 'Q_7', 'Q_8', 'Q_9', 'rms_mean', 'rms_std', 'rms_min', 'rms_max', 'flatness_mean', 'flatness_std', 'flatness_min', 'flatness_max', 'rolloff_mean', 'rolloff_std', 'rolloff_min', 'rolloff_max', 'contrast_mean', 'contrast_std', 'contrast_min', 'contrast_max', 'f1_audio_mean', 'f1_audio_std', 'f1_audio_min', 'f1_audio_max', 'centroid_mean', 'centroid_std', 'centroid_min', 'centroid_max', 'c_mean', 'c_std', 'c_min', 'c_max', 'Q_mean', 'Q_std', 'Q_min', 'Q_max']

In [ ]:
# Exporter en CSV sans l’index
stats.to_csv('/content/drive/MyDrive/Article sound/stats.csv', index=False, encoding='utf-8')